server:
  port: 81 #http://localhost:81/pages/books.html
  
spring:
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/H2_DB/test # http://localhost:81/h2
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: 123456    

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto 
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
logging:
  level:
    root: info
